#!/bin/bash
# update-cloudflare-ips.sh
# Fetches latest Cloudflare IP ranges and updates nginx config
# Run periodically via cron: 0 3 * * 0 /path/to/jarvis-ai/scripts/update-cloudflare-ips.sh

set -e

NGINX_CF_FILE="/etc/nginx/cloudflare-ips.conf"

echo "# Cloudflare IPs - Updated $(date -u +%Y-%m-%dT%H:%M:%SZ)" > /tmp/cloudflare-ips.conf
echo "# Auto-generated by jarvis-ai/scripts/update-cloudflare-ips.sh" >> /tmp/cloudflare-ips.conf
echo "" >> /tmp/cloudflare-ips.conf

# Fetch IPv4 ranges
echo "# IPv4" >> /tmp/cloudflare-ips.conf
for ip in $(curl -s https://www.cloudflare.com/ips-v4); do
    echo "allow $ip;" >> /tmp/cloudflare-ips.conf
done

echo "" >> /tmp/cloudflare-ips.conf

# Fetch IPv6 ranges
echo "# IPv6" >> /tmp/cloudflare-ips.conf
for ip in $(curl -s https://www.cloudflare.com/ips-v6); do
    echo "allow $ip;" >> /tmp/cloudflare-ips.conf
done

echo "" >> /tmp/cloudflare-ips.conf

# Allow localhost for local testing
echo "# Localhost" >> /tmp/cloudflare-ips.conf
echo "allow 127.0.0.1;" >> /tmp/cloudflare-ips.conf
echo "allow ::1;" >> /tmp/cloudflare-ips.conf
echo "" >> /tmp/cloudflare-ips.conf

# Deny all others
echo "# Deny all other IPs" >> /tmp/cloudflare-ips.conf
echo "deny all;" >> /tmp/cloudflare-ips.conf

# Install the config
sudo mv /tmp/cloudflare-ips.conf "$NGINX_CF_FILE"
sudo chmod 644 "$NGINX_CF_FILE"

# Test and reload nginx
if sudo nginx -t 2>&1; then
    sudo systemctl reload nginx
    echo "✓ Cloudflare IPs updated and nginx reloaded"
else
    echo "✗ Nginx config test failed!"
    exit 1
fi
